# K?t n?i Oracle trong Docker (service name: ORCLPDB1)
spring.datasource.url=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Ph?c v? file t?nh
spring.mvc.static-path-pattern=/**
